const STORAGE_NAME = '@CRISTALIAuth';

const COLLECTION_ITEMS = `${STORAGE_NAME}:items`;
const COLLECTION_USER = `${STORAGE_NAME}:user`;
const COLLECTION_TOKEN = `${STORAGE_NAME}:token`;

export {
  COLLECTION_USER,
  COLLECTION_TOKEN,
  COLLECTION_ITEMS
}