const STORAGE_NAME = '@CRISTALIAuth';

const COLLECTION_ITEMS = `${STORAGE_NAME}:items`;
const COLLECTION_USER = `${STORAGE_NAME}:user`;
const COLLECTION_PASSWORD = `${STORAGE_NAME}:password`;
const COLLECTION_TOKEN = `${STORAGE_NAME}:token`;
const COLLECTION_DEVICE_TOKEN = `${STORAGE_NAME}:devicetoken`;

export {
  COLLECTION_USER,
  COLLECTION_TOKEN,
  COLLECTION_ITEMS,
  COLLECTION_DEVICE_TOKEN,
  COLLECTION_PASSWORD
}